#!/usr/bin/env python3
"""Every icon this project ships, from one description of the mark.

The mark is a circle split down the middle: the left half in moonlight, the
right half the same moonlight dimmed to what a surface gives back. A mirror
returns most of the light and not all of it, and that difference is the whole
logo -- there is no glyph, no letter and no gradient inside the mark, because
the smallest place it has to work is a 16 px taskbar button.

Run it when the mark or the palette changes:

    python branding/make-icons.py

It writes, from a 2048 px master rendered with 4x supersampling:

    branding/kagami.svg                     the source of truth for print
    installer/kagami.ico                    exe resource, MSI, shortcut
    receiver/icons/kagami-256.png           hicolor, for the GTK window
    sender/android/app/src/main/res/mipmap-*/ic_launcher.png

Pillow only, which is the one image dependency a Windows box here already has.
"""

from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent

# Moon over deep water. The ground is the window's own, so an icon on a dark
# taskbar reads as a hole cut in it rather than as a tile stuck on top.
MOONLIGHT = (232, 237, 242)
WATER_TOP = (10, 20, 36)
WATER_BOTTOM = (5, 8, 15)
RIM = (28, 42, 68)

# The dim half, as a flat colour rather than an alpha: an icon is composited
# against a taskbar this file cannot see, and 35% of moonlight over anything
# else is a different colour every time.
REFLECTION = tuple(round(m * 0.34 + w * 0.66) for m, w in zip(MOONLIGHT, WATER_TOP))

SS = 4                      # supersampling
MASTER = 512                # before supersampling
RADIUS = 112                # of the rounded square, at MASTER
CIRCLE_R = 150              # of the mark
CENTRE = (256, 250)
SEAM = 11                   # the gap between the halves, at MASTER


def master() -> Image.Image:
    """The mark at MASTER*SS, ready to be resized down to anything."""
    n = MASTER * SS
    img = Image.new("RGBA", (n, n), (0, 0, 0, 0))

    # The ground, as a vertical gradient drawn a row at a time. Pillow has no
    # gradient of its own and a 2048-row loop costs nothing once.
    ground = Image.new("RGBA", (1, n))
    for y in range(n):
        t = y / (n - 1)
        ground.putpixel((0, y), tuple(
            round(a + (b - a) * t) for a, b in zip(WATER_TOP, WATER_BOTTOM)) + (255,))
    ground = ground.resize((n, n))

    # The rounded square is a mask, so the gradient keeps its corners.
    mask = Image.new("L", (n, n), 0)
    ImageDraw.Draw(mask).rounded_rectangle(
        (0, 0, n - 1, n - 1), radius=RADIUS * SS, fill=255)
    img.paste(ground, (0, 0), mask)

    d = ImageDraw.Draw(img)

    # A hairline of sky along the top edge, which is what keeps the tile from
    # dissolving into a dark taskbar.
    d.rounded_rectangle((0, 0, n - 1, n - 1), radius=RADIUS * SS,
                        outline=RIM + (255,), width=max(1, 2 * SS))

    cx, cy = (c * SS for c in CENTRE)
    r = CIRCLE_R * SS
    box = (cx - r, cy - r, cx + r, cy + r)

    # Pillow measures its arcs clockwise from three o'clock, so the right half
    # is -90..90 and the left is what remains.
    d.pieslice(box, 90, 270, fill=MOONLIGHT + (255,))
    d.pieslice(box, -90, 90, fill=REFLECTION + (255,))

    # The seam is ground, not a stroke: the two halves are one object with a
    # gap between them, and a line drawn over them would sit in front instead.
    half = max(1, (SEAM * SS) // 2)
    seam_top = (cx - half, cy - r - SS, cx + half, cy + r + SS)
    d.rectangle(seam_top, fill=(0, 0, 0, 0))
    # And the ground shows through it, because the tile is opaque everywhere
    # else. Re-paste the gradient through a mask of just the seam.
    seam_mask = Image.new("L", (n, n), 0)
    ImageDraw.Draw(seam_mask).rectangle(seam_top, fill=255)
    img.paste(ground, (0, 0), Image.composite(seam_mask, Image.new("L", (n, n), 0), mask))

    return img


def png(img: Image.Image, size: int, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    img.resize((size, size), Image.LANCZOS).save(path)
    print(f"  {path.relative_to(ROOT)}  {size}px")


SVG = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512">
  <!-- Generated by branding/make-icons.py. The mark: a circle split down the
       middle, the left half moonlight and the right half what a surface gives
       back. Edit the script, not this file. -->
  <defs>
    <linearGradient id="water" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#{water_top}"/>
      <stop offset="1" stop-color="#{water_bottom}"/>
    </linearGradient>
    <clipPath id="left">
      <rect x="0" y="0" width="{seam_left}" height="512"/>
    </clipPath>
    <clipPath id="right">
      <rect x="{seam_right}" y="0" width="{seam_rest}" height="512"/>
    </clipPath>
  </defs>
  <rect width="512" height="512" rx="{radius}" fill="url(#water)"/>
  <rect x="1" y="1" width="510" height="510" rx="{radius}" fill="none"
        stroke="#{rim}" stroke-width="2"/>
  <circle cx="{cx}" cy="{cy}" r="{r}" fill="#{moonlight}" clip-path="url(#left)"/>
  <circle cx="{cx}" cy="{cy}" r="{r}" fill="#{reflection}" clip-path="url(#right)"/>
</svg>
"""


def hexof(rgb):
    return "%02x%02x%02x" % rgb


def main() -> None:
    img = master()
    print("writing:")

    (ROOT / "branding").mkdir(exist_ok=True)
    (ROOT / "branding" / "kagami.svg").write_text(SVG.format(
        water_top=hexof(WATER_TOP), water_bottom=hexof(WATER_BOTTOM),
        rim=hexof(RIM), moonlight=hexof(MOONLIGHT), reflection=hexof(REFLECTION),
        radius=RADIUS, cx=CENTRE[0], cy=CENTRE[1], r=CIRCLE_R,
        seam_left=CENTRE[0] - SEAM // 2, seam_right=CENTRE[0] + SEAM // 2,
        seam_rest=512 - CENTRE[0] - SEAM // 2), encoding="utf-8")
    print("  branding/kagami.svg")

    # One .ico with every size Windows asks for. 16 and 32 are the taskbar and
    # the title bar; 256 is what the installer and the Start menu scale from.
    ico = ROOT / "installer" / "kagami.ico"
    ico.parent.mkdir(parents=True, exist_ok=True)
    img.resize((256, 256), Image.LANCZOS).save(
        ico, sizes=[(s, s) for s in (16, 24, 32, 48, 64, 128, 256)])
    print("  installer/kagami.ico  16..256")

    png(img, 256, ROOT / "receiver" / "icons" / "kagami-256.png")

    # Android's five densities. Legacy launcher icons, because the adaptive
    # kind needs a foreground that survives being masked to a circle, and this
    # mark is already a circle -- masking it would eat the seam.
    for size, density in ((48, "mdpi"), (72, "hdpi"), (96, "xhdpi"),
                          (144, "xxhdpi"), (192, "xxxhdpi")):
        png(img, size, ROOT / "sender" / "android" / "app" / "src" / "main"
            / "res" / f"mipmap-{density}" / "ic_launcher.png")


if __name__ == "__main__":
    main()
