// Keeps the Kagami app running while the broadcast extension feeds it frames.
//
// The screen reaches the desktop through this app, not the extension: ReplayKit
// gives the frames to KagamiBroadcast, which writes them to a socket this app
// reads (flutter_webrtc's FlutterBroadcastScreenCapturer), and the WebRTC
// connection that carries them lives here too. Mirroring means the user goes on
// to use other apps, and iOS suspends a backgrounded app within seconds unless
// it has something to do -- after which the socket stops being read and the
// desktop freezes on the last frame.
//
// So while a broadcast is running, this plays silence under the `audio`
// background mode (Info.plist UIBackgroundModes, set by tools/scaffold-ios.sh),
// mixed with other audio so the user's music is not interrupted. Silence, not
// the microphone: nothing here records a sound. It starts and stops on the
// Darwin notifications the extension posts (KagamiBroadcast/SampleHandler.swift,
// the names from DarwinNotificationCenter.swift), so it is running only while
// the red capture indicator is.
//
// +load, because it needs no call from AppDelegate -- which is scaffold,
// regenerated by `flutter create`, and not in this repo.

#import <AVFoundation/AVFoundation.h>
#import <Foundation/Foundation.h>

@interface KagamiKeepAlive : NSObject
@end

static AVAudioEngine *engine;
static AVAudioPlayerNode *player;

static void KagamiBroadcastStarted(CFNotificationCenterRef center, void *observer,
                                   CFNotificationName name, const void *object,
                                   CFDictionaryRef info);
static void KagamiBroadcastStopped(CFNotificationCenterRef center, void *observer,
                                   CFNotificationName name, const void *object,
                                   CFDictionaryRef info);

@implementation KagamiKeepAlive

+ (void)load {
  CFNotificationCenterRef center = CFNotificationCenterGetDarwinNotifyCenter();
  CFNotificationCenterAddObserver(center, NULL, KagamiBroadcastStarted,
                                  CFSTR("iOS_BroadcastStarted"), NULL,
                                  CFNotificationSuspensionBehaviorDeliverImmediately);
  CFNotificationCenterAddObserver(center, NULL, KagamiBroadcastStopped,
                                  CFSTR("iOS_BroadcastStopped"), NULL,
                                  CFNotificationSuspensionBehaviorDeliverImmediately);
}

+ (void)start {
  if (engine) return;
  NSError *error = nil;
  AVAudioSession *session = [AVAudioSession sharedInstance];
  if (![session setCategory:AVAudioSessionCategoryPlayback
                withOptions:AVAudioSessionCategoryOptionMixWithOthers
                      error:&error] ||
      ![session setActive:YES error:&error]) {
    NSLog(@"kagami: keep-alive audio session refused: %@", error);
    return;
  }

  engine = [[AVAudioEngine alloc] init];
  player = [[AVAudioPlayerNode alloc] init];
  [engine attachNode:player];
  AVAudioFormat *format = [engine.mainMixerNode outputFormatForBus:0];
  [engine connect:player to:engine.mainMixerNode format:format];

  // One second of zeros, looped. Zeroed by hand: a fresh buffer's contents are
  // not promised to be anything.
  AVAudioPCMBuffer *silence =
      [[AVAudioPCMBuffer alloc] initWithPCMFormat:format
                                    frameCapacity:(AVAudioFrameCount)format.sampleRate];
  silence.frameLength = silence.frameCapacity;
  for (AVAudioChannelCount c = 0; c < format.channelCount; c++) {
    memset(silence.floatChannelData[c], 0, sizeof(float) * silence.frameLength);
  }

  if (![engine startAndReturnError:&error]) {
    NSLog(@"kagami: keep-alive engine did not start: %@", error);
    engine = nil;
    player = nil;
    return;
  }
  [player scheduleBuffer:silence atTime:nil options:AVAudioPlayerNodeBufferLoops
       completionHandler:nil];
  [player play];
  NSLog(@"kagami: keep-alive on for the broadcast");
}

+ (void)stop {
  if (!engine) return;
  [player stop];
  [engine stop];
  engine = nil;
  player = nil;
  [[AVAudioSession sharedInstance] setActive:NO
                                 withOptions:AVAudioSessionSetActiveOptionNotifyOthersOnDeactivation
                                       error:nil];
  NSLog(@"kagami: keep-alive off");
}

@end

static void KagamiBroadcastStarted(CFNotificationCenterRef center, void *observer,
                                   CFNotificationName name, const void *object,
                                   CFDictionaryRef info) {
  dispatch_async(dispatch_get_main_queue(), ^{ [KagamiKeepAlive start]; });
}

static void KagamiBroadcastStopped(CFNotificationCenterRef center, void *observer,
                                   CFNotificationName name, const void *object,
                                   CFDictionaryRef info) {
  dispatch_async(dispatch_get_main_queue(), ^{ [KagamiKeepAlive stop]; });
}
